# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='led',
            name='time_00',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_01',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_02',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_03',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_04',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_05',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_06',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_07',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_08',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_09',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_10',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_11',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_12',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_13',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_14',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_15',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_16',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_17',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_18',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_19',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_20',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_21',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_22',
        ),
        migrations.RemoveField(
            model_name='led',
            name='time_23',
        ),
        migrations.AddField(
            model_name='led',
            name='box',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Box 1'), (2, 'Box 2')], db_index=True, default=1, verbose_name='Box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='led',
            name='hour_00',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='00:00 - 00:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_01',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='01:00 - 01:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_02',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='02:00 - 02:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_03',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='03:00 - 03:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_04',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='04:00 - 04:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_05',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='05:00 - 05:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_06',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='06:00 - 06:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_07',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='07:00 - 07:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_08',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='08:00 - 08:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_09',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='09:00 - 09:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_10',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='10:00 - 10:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_11',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='11:00 - 11:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_12',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='12:00 - 12:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_13',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='13:00 - 13:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_14',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='14:00 - 14:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_15',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='15:00 - 15:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_16',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='16:00 - 16:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_17',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='17:00 - 17:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_18',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='18:00 - 18:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_19',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='19:00 - 19:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_20',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='20:00 - 20:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_21',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='21:00 - 21:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_22',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='22:00 - 22:59'),
        ),
        migrations.AddField(
            model_name='led',
            name='hour_23',
            field=models.PositiveSmallIntegerField(default=0, help_text='[0-100]% Percent of LED power', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='23:00 - 23:59'),
        ),
    ]
